In [1]:
for n in 1: 10
   A = [i + j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

In [5]:
m = 10
typeof(m)

Int64

In [7]:
n = 10
B = zeros(m, n)

10×10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [8]:
for i in 1:m, j in 1:n
    B[i,j] = i +j
end

In [10]:
B

10×10 Array{Float64,2}:
  2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0
  3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0
  4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0
  5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0
  6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0
  7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0
  8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0
  9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0
 10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0
 11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0

In [11]:
name = "luodeng"

"luodeng"

In [12]:
println("My name is $name")

My name is luodeng


In [13]:
age = 20
println("My age is $age")

My age is 20


## Conditions

In [15]:
x = 90
y = 3
if x > y
    println("$x is greater than $y")
elseif y > x
    println("$y is greater than $x")
else
    println("$y is equal $x")
end

90 is greater than 3


In [16]:
(x > y) && println("$x is greater than $y")

90 is greater than 3


In [17]:
(x < y ) && println("$x is smaller than $y")

false

## Function

In [25]:
function sayhi(name)
     println("Hi $name it is nice to meet you!")
end

sayhi (generic function with 1 method)

In [26]:
sayhi(name)

Hi luodeng it is nice to meet you!


In [27]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [29]:
f(4)

16

In [31]:
println("The Equation 4^2 = $(f(4))")

The Equation 4^2 = 16


We can declare the function in a single line, so without the `end` sambol

In [32]:
sayhi(name) = println("Hi $name, it is nice to meet you!")

sayhi (generic function with 1 method)

In [33]:
sayhi(name)

Hi luodeng, it is nice to meet you!


In [34]:
f(x) = x^2

f (generic function with 1 method)

In [35]:
f(42)

1764

Apart from this, we can declared the `anonymous funtion`

In [38]:
sayhi3 = name->println("Hi $name, it is nice to meet you!")

(::#7) (generic function with 1 method)

In [39]:
f3 = x-> x^2

(::#9) (generic function with 1 method)

In [41]:
f3(42)

1764

In [42]:
sayhi3(name)

Hi luodeng, it is nice to meet you!


### Duck-typing in Julia

"If it quacks like a duck, then it is a duck"

In [43]:
sayhi(99999)

Hi 99999, it is nice to meet you!


In [44]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.904492  0.140736   0.991933 
 0.315818  0.154776   0.0686535
 0.980843  0.0742665  0.888634 

In [45]:
f(A)

3×3 Array{Float64,2}:
 1.83548   0.222745   1.78832 
 0.401875  0.0735015  0.384904
 1.78223   0.215531   1.7677  

In [46]:
v = rand(3)

3-element Array{Float64,1}:
 0.127685
 0.845431
 0.851998

In [47]:
f(v)

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [48]:
B = rand(3, 4)

3×4 Array{Float64,2}:
 0.385579   0.146067  0.772565  0.673754
 0.0577271  0.219787  0.77196   0.699541
 0.607734   0.363019  0.971724  0.898295

In [49]:
f(B)

LoadError: DimensionMismatch("A has dimensions (3,4) but B has dimensions (3,4)")

### Mutating vs. non-mutating functions

Mutating function change the values you put into the function.

While non-mutating function while not change the value you put into the function. Usually with the `!`

In [50]:
v = [3, 5, 2]

3-element Array{Int64,1}:
 3
 5
 2

In [53]:
sort(v)
println(v)
sort!(v)
println(v)

[3, 5, 2]
[2, 3, 5]


In [52]:
v

3-element Array{Int64,1}:
 3
 5
 2

## Broadcasting

By placing a `.` between any function name and its arguments list, we tell the function to broadcast over the elements of the input objects.

Let's look at the different behaviors between `f()` and `f.()` 

In [54]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [57]:
f(A)
# here is the matrix product

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

In [58]:
f.(A)
# here is the broadcast on each element in A

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

In [64]:
using Colors

In [65]:
palette = distinguishable_colors(100)

In [69]:
rand(palette, 5, 5)